name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Ejecutar deploy simulado"
        required: false
        default: "no"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests
        run: python -m pytest > resultado_test.txt

      - name: Subir artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resultado_test
          path: resultado_test.txt

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Construir Docker
        run: docker build -t miapp .

  deploy:
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'si'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy simulado
        run: echo "Aplicacion desplegada"